name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd webapp
        docker build -f src/main/docker/Dockerfile.amd64 -t manorrock/siamese:amd64-snapshot .
        docker push manorrock/siamese:amd64-snapshot
    - name: Build arm32v6 image
      run: |
        cd webapp
        docker build -f src/main/docker/Dockerfile.arm32v6 -t manorrock/siamese:arm32v6-snapshot .
        docker push manorrock/siamese:arm32v6-snapshot
    - name: Create multi-arch manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/siamese:snapshot \
          manorrock/siamese:amd64-snapshot \
          manorrock/siamese:arm32v6-snapshot
        docker manifest annotate manorrock/siamese:snapshot \
          manorrock/siamese:amd64-snapshot --os linux --arch amd64
        docker manifest annotate manorrock/siamese:snapshot \
          manorrock/siamese:arm32v6-snapshot --os linux --arch arm
        docker manifest push manorrock/siamese:snapshot
