name: docker-release
on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd webapp
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}}
        docker build -f src/main/docker/Dockerfile -t manorrock/siamese:$VERSION .
        docker push manorrock/siamese:$VERSION
    - name: Build ARM32v6 image
      run: |
        cd webapp
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}}
        docker build -f src/main/docker/Dockerfile.ARM32v6 -t manorrock/siamese:arm32v6-$VERSION .
        docker push manorrock/siamese:arm32v6-$VERSION
